import{a as S,S as q,i}from"./assets/vendor-CucEYOFD.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))s(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const n of r.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&s(n)}).observe(document,{childList:!0,subtree:!0});function a(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function s(e){if(e.ep)return;e.ep=!0;const r=a(e);fetch(e.href,r)}})();const E="56799357-5764c9f004e69503c7bfa7d57",R="https://pixabay.com/api/";async function d(t,o=1,a=15){return await S.get(R+`?page=${o}&per_page=${a}`,{params:{key:E,q:t,image_type:"photo",orientation:"horizontal",safesearch:!0}}).then(s=>s.data)}const $=new q(".gallery a",{captionsData:"alt",captionDelay:250}),m=document.querySelector(".gallery"),l=document.querySelector(".loader");function y(t){const o=t.map(({webformatURL:a,largeImageURL:s,tags:e,likes:r,views:n,comments:v,downloads:P})=>`
      <li class="gallery-item">
        <a class="gallery-link" href="${s}">
          <img class="gallery-image" src="${a}" alt="${e}" />
        </a>
        <div class="gallery-caption">
          <ul class="gallery-caption-list">
            <li class="gallery-caption-item"><span class="caption-label">Likes</span><span>${r}</span></li>
            <li class="gallery-caption-item"><span class="caption-label">Views</span><span>${n}</span></li>
            <li class="gallery-caption-item"><span class="caption-label">Comments</span><span>${v}</span></li>
            <li class="gallery-caption-item"><span class="caption-label">Downloads</span><span>${P}</span></li>
          </ul>
        </div>
      </li>
    `).join("");m.innerHTML+=o,$.refresh()}function B(){m.innerHTML=""}function h(){l&&l.classList.add("active")}function f(){l&&l.classList.remove("active")}function L(){document.querySelector("#load-more").classList.add("active")}function g(){document.querySelector("#load-more").classList.remove("active")}let w="",c=1;const u=15;let p=0;const M=document.querySelector(".form"),A=document.querySelector("#load-more");A.addEventListener("click",O);M.addEventListener("submit",async t=>{t.preventDefault();const o=t.target.elements["search-text"].value.trim();if(!o){i.warning({title:"Warning",message:"Please enter a search query!",position:"topRight"});return}w=o,c=1,p=0,B(),h(),g();try{const a=await d(o,1,u);if(!a.hits||a.hits.length===0){i.error({title:"Error",message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"});return}p=Math.ceil(a.totalHits/u),y(a.hits),b()}catch(a){console.error(a),i.error({title:"Error",message:"An error occurred while fetching images. Please try again later.",position:"topRight"})}finally{f(),t.target.reset()}});function b(){c>=p?(g(),i.warning({title:"Warning",message:"We're sorry, but you've reached the end of search results.",position:"topRight"})):L()}async function O(){c++;try{h(),g();const t=await d(w,c,u);if(!t.hits||t.hits.length===0){i.error({title:"Error",message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"});return}y(t.hits),L(),x()}catch(t){console.error(t),i.error({title:"Error",message:"An error occurred while fetching images. Please try again later.",position:"topRight"})}finally{f(),b()}}function x(){const{height:t}=document.querySelector(".gallery-item").getBoundingClientRect();window.scrollBy({top:2*t,behavior:"smooth"})}
//# sourceMappingURL=index.js.map
