import{a as S,S as q,i as s}from"./assets/vendor-CucEYOFD.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))i(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const n of r.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&i(n)}).observe(document,{childList:!0,subtree:!0});function a(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function i(e){if(e.ep)return;e.ep=!0;const r=a(e);fetch(e.href,r)}})();const B="56799357-5764c9f004e69503c7bfa7d57",M="https://pixabay.com/api/";async function y(t,o=1,a=15){return await(await S.get(M,{params:{key:B,q:t,image_type:"photo",orientation:"horizontal",safesearch:!0,page:o,per_page:a}})).data}const R=new q(".gallery a",{captionsData:"alt",captionDelay:250}),m=document.querySelector(".gallery"),l=document.querySelector(".loader"),c=document.querySelector("#load-more");function f(t){const o=t.map(({webformatURL:a,largeImageURL:i,tags:e,likes:r,views:n,comments:P,downloads:E})=>`
      <li class="gallery-item">
        <a class="gallery-link" href="${i}">
          <img class="gallery-image" src="${a}" alt="${e}" />
        </a>
        <div class="gallery-caption">
          <ul class="gallery-caption-list">
            <li class="gallery-caption-item"><span class="caption-label">Likes</span><span>${r}</span></li>
            <li class="gallery-caption-item"><span class="caption-label">Views</span><span>${n}</span></li>
            <li class="gallery-caption-item"><span class="caption-label">Comments</span><span>${P}</span></li>
            <li class="gallery-caption-item"><span class="caption-label">Downloads</span><span>${E}</span></li>
          </ul>
        </div>
      </li>
    `).join("");m.innerHTML+=o,R.refresh()}function $(){m.innerHTML=""}function h(){l&&l.classList.add("active")}function L(){l&&l.classList.remove("active")}function w(){c&&c.classList.add("active")}function d(){c&&c.classList.remove("active")}let b="",u=1;const p=15;let g=0;const A=document.querySelector(".form"),O=document.querySelector("#load-more");O.addEventListener("click",x);A.addEventListener("submit",async t=>{t.preventDefault();const o=t.target.elements["search-text"].value.trim();if(!o){s.warning({title:"Warning",message:"Please enter a search query!",position:"topRight"});return}b=o,u=1,g=0,$(),h(),d();try{const a=await y(o,1,p);if(!a.hits||a.hits.length===0){s.error({title:"Error",message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"});return}g=Math.ceil(a.totalHits/p),f(a.hits),v()}catch(a){console.error(a),s.error({title:"Error",message:"An error occurred while fetching images. Please try again later.",position:"topRight"})}finally{L(),t.target.reset()}});function v(){u>=g?(d(),s.warning({title:"Warning",message:"We're sorry, but you've reached the end of search results.",position:"topRight"})):w()}async function x(){u++;try{h(),d();const t=await y(b,u,p);if(!t.hits||t.hits.length===0){s.error({title:"Error",message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"});return}f(t.hits),w(),_()}catch(t){console.error(t),s.error({title:"Error",message:"An error occurred while fetching images. Please try again later.",position:"topRight"})}finally{L(),v()}}function _(){const{height:t}=document.querySelector(".gallery-item").getBoundingClientRect();window.scrollBy({top:2*t,behavior:"smooth"})}
//# sourceMappingURL=index.js.map
