import{a as v,S as P,i}from"./assets/vendor-CucEYOFD.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))s(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const n of r.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&s(n)}).observe(document,{childList:!0,subtree:!0});function a(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function s(e){if(e.ep)return;e.ep=!0;const r=a(e);fetch(e.href,r)}})();const S="56799357-5764c9f004e69503c7bfa7d57",q="https://pixabay.com/api/";async function g(t,o=1,a=15){return await v.get(q+`?page=${o}&per_page=${a}`,{params:{key:S,q:t,image_type:"photo",orientation:"horizontal",safesearch:!0}}).then(s=>s.data)}const E=new P(".gallery a",{captionsData:"alt",captionDelay:250}),d=document.querySelector(".gallery"),l=document.querySelector(".loader");function m(t){const o=t.map(({webformatURL:a,largeImageURL:s,tags:e,likes:r,views:n,comments:w,downloads:b})=>`
      <li class="gallery-item">
        <a class="gallery-link" href="${s}">
          <img class="gallery-image" src="${a}" alt="${e}" />
        </a>
        <div class="gallery-caption">
          <ul class="gallery-caption-list">
            <li class="gallery-caption-item"><span class="caption-label">Likes</span><span>${r}</span></li>
            <li class="gallery-caption-item"><span class="caption-label">Views</span><span>${n}</span></li>
            <li class="gallery-caption-item"><span class="caption-label">Comments</span><span>${w}</span></li>
            <li class="gallery-caption-item"><span class="caption-label">Downloads</span><span>${b}</span></li>
          </ul>
        </div>
      </li>
    `).join("");d.innerHTML+=o,E.refresh()}function R(){d.innerHTML=""}function $(){l&&l.classList.add("active")}function B(){l&&l.classList.remove("active")}function y(){document.querySelector("#load-more").classList.add("active")}function h(){document.querySelector("#load-more").classList.remove("active")}let f="",c=1;const u=15;let p=0;const M=document.querySelector(".form"),A=document.querySelector("#load-more");A.addEventListener("click",O);M.addEventListener("submit",async t=>{t.preventDefault();const o=t.target.elements["search-text"].value.trim();if(!o){i.warning({title:"Warning",message:"Please enter a search query!",position:"topRight"});return}f=o,c=1,p=0,R(),$(),h();try{const a=await g(o,1,u);if(!a.hits||a.hits.length===0){i.error({title:"Error",message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"});return}p=Math.ceil(a.totalHits/u),m(a.hits),L()}catch(a){console.error(a),i.error({title:"Error",message:"An error occurred while fetching images. Please try again later.",position:"topRight"})}finally{B(),t.target.reset()}});function L(){return c>=p?(h(),i.warning({title:"Warning",message:"We're sorry, but you've reached the end of search results.",position:"topRight"}),!1):(y(),!0)}async function O(){if(c++,!!L())try{const t=await g(f,c,u);if(!t.hits||t.hits.length===0){i.error({title:"Error",message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"});return}m(t.hits),y(),x()}catch(t){console.error(t),i.error({title:"Error",message:"An error occurred while fetching images. Please try again later.",position:"topRight"})}}function x(){const{height:t}=document.querySelector(".gallery-item").getBoundingClientRect();window.scrollBy({top:2*t,behavior:"smooth"})}
//# sourceMappingURL=index.js.map
